language: python
git:
  depth: 1
install:
  - pip install -r requirements.txt
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install codecov 
# command to run tests
script:
  - python -m unittest discover -p "*_test.py"
  - coverage run fraction_test.py
after_success:
  - export CODECOV_TOKEN="4a985a50-ba43-49c9-a988-e57e9676ab8b"
  - codecov